
kallisto:

    # kallisto indexed transcriptome
    transcriptome: ?!

    # the gtf file that the index was
    # built from is used to map transcript
    # ids to gene ids - for tximport
    transcripts_gtf: ?!

    nthreads: 1

    # Check the kallisto options. Include the stranded
    # information here
    options: --rf-stranded