
kallisto:

    # kallisto indexed transcriptome
    transcriptome: ?!

    nthreads: 1
    job_mem: 2Gb

    # Check the kallisto options. Include the stranded
    # information here
    options: --rf-stranded